ValveSoftware/source-sdk-2013

src/game/server/SkyCamera.cpp

Self-explanatory, [matches the fog controller](https://github.com/ValveSoftware/source-sdk-2013/blob/master/src/game/server/fogcontroller.cpp#L375)

Fix radial fog not being enabled in 3D sky on official maps

---

src/game/server/tf/player_vs_environment/tf_population_manager.cpp
src/game/server/tf/player_vs_environment/tf_population_manager.h
src/game/server/tf/player_vs_environment/tf_populator_spawners.cpp
src/game/server/tf/player_vs_environment/tf_populators.cpp
src/game/shared/tf/tf_gamerules.cpp
src/game/shared/tf/tf_gamerules.h

Currently the number of maximum robots in MvM is hardcoded to 22, which is unfortunate given TF2 supports 101 players. This PR makes the limit controlled by a convar named `tf_mvm_max_invaders`

Add convar to customize maximum MvM robots

---

src/game/server/player.cpp
src/public/const.h

This PR fixes an oversight in all multiplayer Source 2013 games (TF, CS:S, DoD:S, HL1MP, HL2MP) caused by `PLAYER_FLAG_BITS` being set to a lower value than needed, which resulted in some player flags not being sent to clients.
For instance, it created a desync error when a player was pushed by a `trigger_push` entity, causing the client's view to be offset from the real position and breaking some community maps (example below).
The solution is to raise the value of the `PLAYER_FLAG_BITS` macro in `src/public/const.h` to 32 bits so no flags will be truncated.
https://github-production-user-asset-6210df.s3.amazonaws.com/48454166/417359472-d2e2ad0b-bd05-413c-b1d8-0d6da6898866.mp4
https://github-production-user-asset-6210df.s3.amazonaws.com/48454166/417361827-4f7b8ef0-a68a-43fa-a7ae-b60639492 …

all MP games: Fix PLAYER_FLAG_BITS truncating CBasePlayer::m_fFlags sent to clients

---

src/game/client/tf/c_tf_player.cpp

Pressing middle mouse click (mouse3) in the PASS Time gamemode kicks the client immediately. This is because it sends a voicecommand every frame when the button is pressed, for which the server then promptly kicks the client for spamming commands. The PR fixes this by only sending the voicecommand when mouse3 is pressed, not held.

Fix middle mouse kicking players out of the server in PASS Time

---

src/game/shared/tf/tf_player_shared.cpp
src/game/shared/tf/tf_weapon_compound_bow.cpp
src/game/shared/tf/tf_weapon_compound_bow.h
src/game/shared/tf/tf_weaponbase.h

partially fixes this issue: https://github.com/ValveSoftware/Source-1-Games/issues/6017
(in the vids below, i press jump immediately after charging 3 times, then jump immediately after releasing 3 times, then jump immediately after holstering 3 times)
unfixed, net_fakelag 100:
https://github.com/user-attachments/assets/fca19788-6847-4e5e-b1ad-0991ddb84d9d
fixed, net_fakelag 100:
https://github.com/user-attachments/assets/f88c1153-b433-41fd-8479-9d69af8aba47
this pr adds CTFWeaponBase::OwnerCanJump (similar to the existing CTFWeaponBase::OwnerCanTaunt)

[TF2] Fix prediction for jumping when huntsman is charged/released

---

src/game/client/tf/clientmode_tf.cpp

Currently, only sprays and files in the `download/user_custom` path are removed on shutdown if `tf_delete_temp_files` is enabled, leaving temporary sound files from the oft-forgotten "jingle" feature untouched. These files are also commonly referred to as "sound sprays".
This PR fixes this by also removing these files on shutdown if the said cvar is enabled.
Resolves https://github.com/ValveSoftware/Source-1-Games/issues/4014

[TF2] Remove temporary player jingle files if tf_delete_temp_files is enabled

---

src/game/server/team_control_point_master.cpp

The `game_round_win`'s `RoundWin` input would make the server on King of the Hill maps enter an infinite loop forever.
This patch fixes this.
Fixes https://github.com/ValveSoftware/Source-1-Games/issues/4254

tf2: Fix crash with game_round_win in koth

---

src/game/shared/hl2mp/weapon_357.cpp

This PR addresses an issue where firing the .357 causes the player’s view angles to "snap" back to the firing angles due to the server processing this. This becomes particularly problematic at higher pings, where firing the weapon while moving your view results in your view snapping back to the firing angles after this many milliseconds corresponding to the player's latency.
Some server ops resolve this by disabling the view angle snapping entirely on the server, which does prevent the issue. However, this also removes the intended randomization in where the crosshair ends up after the weapon’s disorienting recoil effect, reducing the intended gameplay feedback.
The fix here moves the view angle snapping logic to the client-side, preventing the annoying snapping caused by the server …

[HL2DM] Move .357 snap after firing to client-side

---

src/game/server/tf/tf_player.cpp
src/game/shared/tf/tf_player_shared.cpp
src/game/shared/tf/tf_player_shared.h
src/game/shared/tf/tf_weapon_rocketpack.cpp
src/game/shared/tf/tf_weapon_rocketpack.h

fixes this issue partially: https://github.com/ValveSoftware/source-1-games/issues/6017
no more rubberbanding for the jetpack launches and sounds now play without delay or playing multiple times
unfixed, net_fakelag 100:
https://github.com/user-attachments/assets/0cc8ffbd-dce5-41b2-ae3a-47d98704c08f
fixed, net_fakelag 100:
https://github.com/user-attachments/assets/77312921-ad9c-4eb2-adcc-784ada681f30
CAVEATS:
deploy/holster is still unpredicted, because when i make it predicted it can cause a materialsystem crash that idk how to debug
the crash happens rarely when you deploy the jetpack and it swaps the hud icon in tf_hud_itemeffectmeter
commenting out this line stops the crash from occurring (because it keeps the icon constant): …

[TF2] Fix prediction for thermal thruster

---

src/launcher_main/launcher_main_mod_hl2mp.rc
src/launcher_main/launcher_main_mod_tf.rc

This changes the file included in the .rc files for the launcher exe from afxres.h to winres.h, in order to allow users without MFC installed to compile the game. This does not remove it from other util .rc files which do depend on MFC.
afxres is the MFC equivalent of winres, and old versions of Visual Studio would create rc files with that included by default instead of winres, even if the project did not use MFC.

Remove MFC dependency in the launcher exe

---

src/game/server/NextBot/NextBot.h
src/game/server/baseentity.h

This implements a boolean in baseentity.h that functions similarly to IsNPC or IsPlayer. When referencing a NextBot NPC or Player, the IsNextBot() value will return true.
This was originally made for my HL2 NPC awareness of NextBot feature to my personal fork and my FIREFIGHT RELOADED mod (https://github.com/BitlDevelopmentStudios/source-sdk-2013-bds-base/commit/14091c39328fd5ee02ec8967881c026157727573), but I decided to send a PR of IsNextBot() and not the senses implementation as I felt that the feature would only suit specific mods that have working NPCs in multiplayer or incorporating NextBot NPCs into singleplayer. IsNextBot() is general enough that I see it getting implemented in an SDK branch.

Implement IsNextBot()

---

src/game/client/tf/tf_hud_match_status.cpp

Fixes https://github.com/ValveSoftware/Source-1-Games/issues/3516
Code has been updated to refresh the Match Status HUD doors' skin and submodel at the conclusion of a match. Check is similar to what is performed at start of match.
Due to Casual Mode's original behavior (no late joining, no abandoning) skin and submodel are currently only set at the beginning of a match for all gamemodes that support it. Late-joiners in Casual mode will see the Competitive logo at the end of the match if the model was not updated at the start of a previous match.

[TF2] Fix for Casual late-joiners seeing Competitive logo on Match Status HUD doors

---

src/game/client/tf/vgui/tf_mapinfomenu.cpp

TF2 supports a feature, which [lets mappers change the whiteboard text](https://developer.valvesoftware.com/wiki/TF2/Modifying_the_Mission_Briefing), that you see upon loading a map.
Due to an oversight, this feature doesn't work in Versus Saxton Hale and Zombie Infection, because of their mission briefings being tied to the map prefix, and the check for said prefix being done before the check for the custom mission briefing text files.
This PR moves the check to be after the text file check, which makes custom mission briefings work again.

[TF2] Allow custom mission briefings in vsh and zi

---

src/game/shared/tf/tf_gamerules.cpp

Replaced semicolon with plus operator to allow score calculation for currency collected in the MvM gamemode

[TF2]Fix typo in MVM score calculation 

---

src/game/shared/saverestore.cpp

shared: Missed break in logging character field save data causing incorrect logging

---

src/game/server/tf/bot/behavior/engineer/tf_bot_engineer_build_teleport_entrance.cpp

Fixes engineer bots standing in their spawn without doing anything on Capture the Flag maps, by letting them head to their flag capture zone instead of waiting for a control point that doesn't exist.

[TF2] Fix engineer bots softlocking on CTF maps

---

src/game/server/tf/tf_player.cpp

As part of the Vita-Saw's weapon gimmick of collecting organs from players, organ props are spawned whenever a player is hit with the Vita-Saw. However, the check for when to spawn an organ prop is imprecise; currently, TF2 will spawn a prop when a player takes damage if their attacker is a Medic holding the Vita-Saw. This logic means that if a Medic shoots a projectile (ex. a Crusader's Crossbow syringe) and switches to the Vita-Saw before the projectile hits a player, the projectile hit will cause an organ prop to spawn. This is presumably unintended, as such a hit does not increment a player's organ count.
This PR makes it so organ props will only spawn when a player takes damage if the _attacking weapon_ is the Vita-Saw, preventing the prior case from spawning props.

[TF2] Fix organ props spawning from non-Vita-Saw damage

---

src/game/client/particlemgr.cpp

The title of this PR should hopefully explain it well. The constructor for `CParticleEffectBinding` calls a function that uses the value of its field `m_flParticleCullRadius` before the field is initialized. The offending function call occurs on this line:
https://github.com/ValveSoftware/source-sdk-2013/blob/48809cb86c0990b35f190404aa85d0483d306fa4/src/game/client/particlemgr.cpp#L149
This results in multiple (although seemingly ignorable) assertion errors occurring when loading maps in a fresh copy of the TF2 SDK after compiling it with the debug profile.
This PR fixes this by initializing `m_flParticleCullRadius` to a dummy value before its initial use (where it is then overwritten).

Fix uninitialized field use in `CParticleEffectBinding`

---

src/game/client/client_thinklist.h

ulong/long is 4 bytes on Windows and 8 bytes on Linux/macOS

Fix type cast warning caused by pointer size mismatch

---

src/game/server/tf/entity_currencypack.cpp

MvM money is automatically collected in various cases where its position is unfair for players to collect themselves.
There is a case where robots can drop money in their own spawn, which can prove hard or impossible to acquire, so add an additional check for money that is in a spawn room, just like it is already done for trigger_hurt.

[TF2] gameplay: automatically collect MvM money in respawn room

---

src/game/client/tf/tf_hud_match_status.cpp

Hotfix for recently added fix; Added check for if the versus doors haven't been initialized yet before setting skin/submodel
Current code from PR #893 does not check if the versus door model has been initialized yet. This results in the submodel not updating correctly upon the first time it is loaded in client, resulting in the bugged appearance seen below:
Issue currently seems to resolve itself after the first time this is triggered (as the model has since been initialized).
Repro steps:
* Join a casual game in-progress from a freshly started TF2 client
* Play match until completion

[TF2] Hotfix for PR #893; Fix for submodel not updating correctly upon Casual late-join

---

src/game/shared/tf/tf_gamemovement.cpp

This is very rare to happen nowadays. But what would happen is an MvM bot would get stuck in world geometry while trying to leave spawn. If the bot stays stuck for 10 seconds, the game prints a dev message saying `A robot is interpenetrating a solid - killed!` and the game applies 999999.9 damage, the issue here is that since the bot is inside of the spawn that damage gets nullified because the bot still has the uber spawn condition. CommitSuicide does not do this and instantly kills the bot even with spawn uber protection. As such, this change is here to prevent those rare moments.
For reference on this bug, see https://github.com/ValveSoftware/Source-1-Games/issues/4620

[TF2] Update 10 second stuck MvM bots to use CommitSuicide over TakeDamage for rare spawn softlocks

---

src/game/shared/tf/tf_item_powerup_bottle.cpp
src/game/shared/tf/tf_weaponbase.cpp
src/game/shared/tf/tf_weaponbase.h

This fixes ammo canteens just not affecting energy weapons which include the Cow Mangler 5000, The Righteous Bison, and The Pomson 6000.

[TF2] Fix MvM ammo canteens not affecting energy weapons

---

src/game/shared/tf/tf_gamemovement.cpp
src/game/shared/tf/tf_player_shared.cpp

Fixes https://github.com/ValveSoftware/Source-1-Games/issues/2455
As described in above bug, TF_COND_PARACHUTE_DEPLOYED is not removed upon landing, but only upon using the jump button while grounded. This can lead to a case where the player has used the parachute, landed, and then becomes airborne without the jump button again, resulting in them being unable to deploy the parachute despite being fully grounded.
This patch moves the removal of the condition to the same case as TF_COND_PARACHUTE_ACTIVE's removal when grounded. It also prevents using the jump button to add the parachute conditions while grounded, in order to prevent the client from receiving the parachute condition for a frame every time they jump.

[TF2] Fix player not being able to deploy parachute after landing and becoming airborne without jump button

---

src/game/client/tf/c_obj_sentrygun.cpp
src/game/client/tf/c_obj_sentrygun.h

Wrangler shields don't attach to sentryguns that are parented to a moving object, causing them to float ominously. This PR addresses that by parenting the shield to the sentrygun as well. This is a common problem with community maps that have moving platforms, vehicles etc
Before:
https://github.com/user-attachments/assets/a2287103-b0a6-4ad5-8786-9ce4ed67d9ac
After:
https://github.com/user-attachments/assets/31ce13c9-8c73-4a8b-8f31-1a398205f6fb

Fix Wrangler shield not moving with parented sentrygun

---

src/game/server/info_camera_link.cpp
src/game/server/point_camera.cpp
src/game/server/point_camera.h

The newly-added map `koth_boardwalk` features "mirrors" in the map, which is an effect created with the `point_camera` entity
However, in populated servers this doesn't work quite right. The mirrors will sometimes display fine, other times it will be skipping frames, and sometimes it won't refresh at all.
This is caused by an oversight in the visibility code for point_camera. The intention is to only transmit the camera to players who are in PVS of either the camera or its link, but this visibility state is calculated before the engine runs transmit checks for players. and there is only one visibility state. When the engine runs the transmit checks for all players later, it will use this singular visibility state and it's value will be whatever was calculated for the *last* player that …

Fix point_camera transmit state in multiplayer

---

src/game/shared/voice_status.cpp

An oversight would cause it to fetch only the lowest 32 players' infos instead of the correct index.
This would result in something like `vban 2 2 2 2` instead of `vban 2 0 0 0` when muting player 2 (muting player 34+66+98 in the process), and would prevent muting players above index 33 correctly as those would not send any vban.
Tested with player indices >33 on live TF2 vs this patch: without the patch, muting player index 36 does nothing; with the patch the player gets muted properly. The outputs of voice_clientdebug and voice_serverdebug also print the expected (incorrect) values in live TF2 and (correct) values in patched version.

[ALL] Fix CVoiceStatus::UpdateServerState not sending the correct vban state from the client
